ovirt-ha-agent: service: be nice on node
Avoid to start the service if any configuration file
is missing.
Avoid to display error messages on Node where the service
is enabled by default and started ad boot before hosted engine
setup execution.

Change-Id: Id53f2afb89405fb771df6ac2f3668e3d8616cac1
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1164226
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

diff --git a/initscripts/ovirt-ha-agent.init.in b/initscripts/ovirt-ha-agent.init.in
--- a/initscripts/ovirt-ha-agent.init.in
+++ b/initscripts/ovirt-ha-agent.init.in
@@ -40,9 +40,15 @@ start()
 {
     [ -x $AGENT ] || exit 5
     if [ ! -f $ENGINE_SETUP_CONF_FILE -o ! -f $VM_CONF_FILE ]; then
-        echo "Configuration by ovirt-hosted-engine-setup is required"
-        echo "Files: $ENGINE_SETUP_CONF_FILE $VM_CONF_FILE"
-        exit 6
+        if [ -f /etc/default/ovirt ]; then
+            # See https://bugzilla.redhat.com/1164226
+            echo -n "Not starting $prog on Node before deployment"
+            exit 0
+        else
+            echo "Configuration by ovirt-hosted-engine-setup is required"
+            echo "Files: $ENGINE_SETUP_CONF_FILE $VM_CONF_FILE"
+            exit 6
+        fi
     fi
     echo -n $"Starting $prog: "
     $AGENT $OPTIONS && success || failure
